 services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    expose:
      - "3000"
    command: ["node", "/app/dist/index.js"]