 services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "3100:3100"
    expose:
      - "31000"
    command: ["node", "/app/dist/index.js"]