name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust this to your default b ranch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        run: corepack enable pnpm

      - name: Start SSH Agent and Add Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Test SSH Connection
        run: ssh -o StrictHostKeyChecking=no root@195.35.6.171 'echo "SSH connection successful!"'

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint

      - name: Run Prettier
        run: pnpm format

      - name: Run Docker build
        run: docker build --no-cache . -t myapp-test

      - name: Copy
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude '/node_modules'  ./ root@195.35.6.171:/var/www/hono/
        shell: bash

      
      - name: Redeploy application
        run: |
          ssh -o StrictHostKeyChecking=no root@195.35.6.171 << EOF
            cd /var/www/hono/
            docker-compose down
            docker-compose up --build -d
          EOF
        shell: bash
